name: todo-app
description: A simple todo list app for ChatGPT using OpenAI Apps SDK
execution:
  engine: asyncio
  environment:
    WIDGET_ASSET_BASE: https://haniehz1.github.io/todo_app/widget
    WIDGET_ASSET_VERSION: "1"
logging:
  level: INFO
